import { TranslationKey } from './contexts/LanguageContext';

export interface Project {
  id: string;
  titleKey: TranslationKey;
  images: string[];
}

export const projects: Project[] = [
    { 
      id: 'puente-romano',
      titleKey: 'projectPuenteRomano',
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%20143.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%207.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%208.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2013.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2014.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2015.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2016.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2017.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2018.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2019.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2020.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2021.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2022.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%2023.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FPuente%20Romano%2FAedificia%20Nobile%20144.jpg?alt=media',
      ]
    },
    { 
      id: 'playa-alicate', 
      titleKey: 'projectPlayaAlicate', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2038.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2039.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2040.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2041.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2042.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2043.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2044.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2FAlicate%20playa%2FAedificia%20Nobile%2045.jpg?alt=media',
      ]
    },
    { 
      id: 'apartamento-morera', 
      titleKey: 'projectApartamentoMorera', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2092.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2093.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2094.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2095.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2096.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2097.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2098.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%2099.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20100.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20101.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20102.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20103.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20104.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20105.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20106.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20107.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20108.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20109.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20110.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20111.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20112.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20130.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20131.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20132.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fapartament%20morera%2FAedificia%20Nobile%20133.jpg?alt=media',
      ]
    },
    { 
      id: 'bahia-alcantara', 
      titleKey: 'projectBahiaAlcantara', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20alcantara%2FAedificia%20Nobile%2056.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20alcantara%2FAedificia%20Nobile%2057.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20alcantara%2FAedificia%20Nobile%2058.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20alcantara%2FAedificia%20Nobile%2059.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20alcantara%2FAedificia%20Nobile%2060.jpg?alt=media',
      ] 
    },
    { 
      id: 'bahia-marbella', 
      titleKey: 'projectBahiaMarbella', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%204.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%205.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%206.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%209.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%2010.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%2011.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%2012.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%20140.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%20141.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fbahia%20Marbella%2FAedificia%20Nobile%20142.JPG?alt=media',
      ] 
    },
    { 
      id: 'el-higueron', 
      titleKey: 'projectElHigueron', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2085.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2084.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2086.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2087.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2088.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2089.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2090.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fel%20higueron%2FAedificia%20Nobile%2091.jpg?alt=media',
      ] 
    },
    { 
      id: 'marbella-country-club', 
      titleKey: 'projectMarbellaCountryClub', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%202.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%203.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2053.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2054.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2055.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2065.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2066.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2067.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2068.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2069.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2070.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2071.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fmarbella%20country%20club%2FAedificia%20Nobile%2072.jpg?alt=media',
      ] 
    },
    { 
      id: 'piedra-blanca', 
      titleKey: 'projectPiedraBlanca', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20147.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2024.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2025.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2026.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2027.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2028.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2029.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2030.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2031.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2032.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2033.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2034.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2035.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2036.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2037.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2046.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2047.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2048.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2049.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2050.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2051.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2052.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2061.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2062.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2063.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%2064.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20119.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20120.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20134.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20135.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20136.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20137.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20138.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20139.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20145.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20146.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpiedra%20blanca%2FAedificia%20Nobile%20148.jpg?alt=media',
      ] 
    },
    { 
      id: 'piscina-la-resina', 
      titleKey: 'projectPiscinaLaResina', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20124.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%201.JPG?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20113.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20114.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20115.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20116.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20117.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20118.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20121.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20122.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20123.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20125.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20126.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20127.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20128.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Fpool%20la%20resina%2FAedificia%20Nobile%20129.jpg?alt=media',
      ] 
    },
    { 
      id: 'torre-real', 
      titleKey: 'projectTorreReal', 
      images: [
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2076.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2073.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2074.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2075.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2077.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2078.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2079.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2080.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2081.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2082.jpg?alt=media',
        'https://firebasestorage.googleapis.com/v0/b/aedificia-nobile.firebasestorage.app/o/Trabajos%20terminados%2Ftorre%20real%2FAedificia%20Nobile%2083.jpg?alt=media',
      ] 
    },
];